### ISSUE TITLE
DFS not supported in service mode, but works in command line mode

### ISSUE THREAD

**Issue by Tummi23** [AndMu/YiScanner#16]
Hi,

 the issue I'm trying to solve is that when running from command line everything works fine and when running as a service - no files are downloaded. My config is pretty basic:

```
{
  "Scan": 60,
  "Timeout": 600,
  "Output": {
    "Compress": false,
    "Images": false,
    "Out": "x:\\HDDs-F\\!Kamery"
  },
  "Archive": 30,
  "Action": null,
  "AutoDiscovery": {
    "On": true,
    "NetworkMask": "192.168.0.0/255.255.255.0"
  },

  "YiFtp": {
    "Path": "/tmp/sd/record/",
    "Password": "",
    "Login": "root",
    "FileMask": "*.mp4"
  },
}
```

I enabled debug logging (thank you for the nlog.config :D) and when running as a service:
 
```
2019-05-15 22:17:40.7637 [DEBUG] [NewFilesPredicate] [12] Can download (True): /tmp/sd/record/2019Y05M15D20H/16M00S.mp4
2019-05-15 22:17:40.7837 [ERROR] [FtpDownloader] [12] System.IO.DirectoryNotFoundException: Could not find a part of the path 'x:\HDDs-F\!Kamery\YI-Outdoor-Camera-1080p\2019Y05M15D20H'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.DirectoryInfo.Create()
   at Wikiled.Common.Extensions.DirectoryInfoExtensions.EnsureDirectoryExistence(DirectoryInfo directory)
   at Wikiled.Common.Extensions.DirectoryInfoExtensions.EnsureDirectoryExistence(String path)
   at Wikiled.YiScanner.Client.VideoHeaderExtensions.GetPath(VideoHeader header, String destination)
   at Wikiled.YiScanner.Destinations.FileDestination.IsDownloaded(VideoHeader header)
   at Wikiled.YiScanner.Downloader.FtpDownloader.<ProcessFile>d__7.MoveNext()
2019-05-15 22:17:40.8097 [INFO] [MonitoringInstance] [12] Done!
2019-05-15 22:17:47.1111 [DEBUG] [DynamicHostManager] [26] ScanFtp
```

Works fine from command line:

```
2019-05-15 22:13:33.4366 [INFO] [FtpDownloader] [14] Connecting: 192.168.0.221
2019-05-15 22:13:33.5776 [INFO] [FtpDownloader] [14] Connected: 192.168.0.221!
2019-05-15 22:13:35.7917 [DEBUG] [DynamicHostManager] [16] ScanFtp
2019-05-15 22:13:49.3235 [DEBUG] [NewFilesPredicate] [14] Can download (True): /tmp/sd/record/2019Y05M15D20H/09M00S.mp4
2019-05-15 22:13:49.3595 [INFO] [FtpDownloader] [14] Downloading </tmp/sd/record/2019Y05M15D20H/09M00S.mp4> from [YI-Outdoor-Camera-1080p]
2019-05-15 22:13:51.8886 [INFO] [FtpDownloader] [23] Download Success:True Message:2.375 seconds (measured here), 1.60 Mbytes per second: Type:PositiveCompletion Code:226 From: [YI-Outdoor-Camera-1080p]
2019-05-15 22:13:51.8956 [DEBUG] [NewFilesPredicate] [23] Can download (True): /tmp/sd/record/2019Y05M15D20H/10M00S.mp4

```

The Service is configured to run as the same user I'm logged in when doing the command line test.  I'm using mounted DFS to save the files. I wasn't sure if it's related as it works fine from command line.  I did a quick test on a local drive and... success ;)

```
2019-05-15 22:26:31.6331 [DEBUG] [NewFilesPredicate] [22] Can download (True): /tmp/sd/record/2019Y05M15D20H/25M00S.mp4
2019-05-15 22:26:31.6521 [INFO] [FtpDownloader] [22] Downloading </tmp/sd/record/2019Y05M15D20H/25M00S.mp4> from [YI-Outdoor-Camera-1080p]
2019-05-15 22:26:34.3493 [INFO] [FtpDownloader] [30] Download Success:True Message:2.599 seconds (measured here), 1.52 Mbytes per second: Type:PositiveCompletion Code:226 From: [YI-Outdoor-Camera-1080p]
2019-05-15 22:26:34.3493 [INFO] [MonitoringInstance] [30] Done!
2019-05-15 22:26:38.1555 [DEBUG] [DynamicHostManager] [28] ScanFtp

```

Do you have any ideas why there's such difference in the behavior?

BR,
T.

**Comment by AndMu** [comment]
Are you sure x:\\HDDs-F\\!Kamery is accessible to the service?
Is it network disk or physical?
Are you running service using user account?

**Comment by Tummi23** [comment]
At this point I'm doing all the tests as administrator with full access to everything. Service is configured to run as administrator (not the default "Local system account"). 
It's a network disk (a DFS namespace mounted as X drive). 

I was playing with storage path like `\\storage\!Kamery` but no to avail. Maybe too many/too few  backslashes? Doing additional tests now.

Thank you for a blazingly fast response ;)

T.

//edit
Storage path like this
`   "Out": "\\\\hdds\\Kamera\\a"
`
works OK in cmd:
```
Connected: 192.168.0.221!
Can download (True): /tmp/sd/record/2019Y05M15D20H/47M00S.mp4
Downloading </tmp/sd/record/2019Y05M15D20H/47M00S.mp4> from [YI-Outdoor-Camera-1080p]
ScanFtp
Download Success:True Message:3.222 seconds (measured here), 1.26 Mbytes per second: Type:PositiveCompletion Code:226 From: [YI-Outdoor-Camera-1080p]
Can download (True): /tmp/sd/record/2019Y05M15D20H/48M00S.mp4
Downloading </tmp/sd/record/2019Y05M15D20H/48M00S.mp4> from [YI-Outdoor-Camera-1080p]
Download Success:True Message:3.714 seconds (measured here), 1.08 Mbytes per second: Type:PositiveCompletion Code:226 From: [YI-Outdoor-Camera-1080p]
Done!
ScanFtp
```
and also in service mode:
```
2019-05-15 22:53:31.5588 [INFO] [FtpDownloader] [16] Connected: 192.168.0.221!
2019-05-15 22:53:43.1424 [DEBUG] [NewFilesPredicate] [16] Can download (True): /tmp/sd/record/2019Y05M15D20H/52M00S.mp4
2019-05-15 22:53:43.1734 [INFO] [FtpDownloader] [16] Downloading </tmp/sd/record/2019Y05M15D20H/52M00S.mp4> from [YI-Outdoor-Camera-1080p]
2019-05-15 22:53:45.7166 [INFO] [FtpDownloader] [24] Download Success:True Message:2.443 seconds (measured here), 1.64 Mbytes per second: Type:PositiveCompletion Code:226 From: [YI-Outdoor-Camera-1080p]
2019-05-15 22:53:45.7366 [INFO] [MonitoringInstance] [24] Done!
2019-05-15 22:53:50.5108 [DEBUG] [DynamicHostManager] [32] ScanFtp

```

1 more test - with "!" in storage path, just to rule this out.
`"Out": "\\\\hdds\\Kamera\\!a"`
it works fine:
```
2019-05-15 22:58:26.1056 [DEBUG] [NewFilesPredicate] [28] Can download (True): /tmp/sd/record/2019Y05M15D20H/57M00S.mp4
2019-05-15 22:58:26.1386 [INFO] [FtpDownloader] [28] Downloading </tmp/sd/record/2019Y05M15D20H/57M00S.mp4> from [YI-Outdoor-Camera-1080p]
2019-05-15 22:58:28.8918 [INFO] [FtpDownloader] [19] Download Success:True Message:2.636 seconds (measured here), 1.56 Mbytes per second: Type:PositiveCompletion Code:226 From: [YI-Outdoor-Camera-1080p]
2019-05-15 22:58:28.9088 [INFO] [MonitoringInstance] [19] Done!

```

T.

**Comment by AndMu** [comment]
Try with a forward slash //storage/!Kamery.
On my service I use:
"//data/CCTV/Monitor"

Regarding mapped disk - several problems can be. And that is more windows specific problem:
a) The mapped disk is not visible to the service (https://support.asperasoft.com/hc/en-us/articles/216127818-How-to-map-network-shares-into-drives-to-a-Windows-service-permanently) 
b) Service fails for some reason to create a directory (I would recommend to check Event View, maybe it has more details)

I would recommend using:  **"//storage/!Kamery"**

**Comment by AndMu** [comment]
You can use a doulbe backslash, but I would recommend single forward.

**Comment by Tummi23** [comment]
Gotta love MS :)
I guess I'll stick to the \\\\ (or // :D) workaround. I just really wanted to get rid of all the shared folders in the env., hence the DFS.

Thank you for your help.


P.S. A tip for all potential readers - I scheduled a daily sync task in task scheduler to download all the missing files. Sometimes it comes in handy (unstable WiFi signal). 
`Wikiled.YiScanner.exe Download -Cameras=YI-Outdoor-Camera-1080p -Hosts=192.168.0.221 -Out=x:\HDDs-F\!Kamery\`

BR,
T.

**Comment by AndMu** [comment]
P.S.
double Backslash is not an MS problem, it is a limitation of JSON file format.
